---
title: "Final Data set"
author: "Eric Rupinski"
date: "1/5/2022"
output:
  word_document: default
  html_document: default
---

```{r}

#Read in libraries:
library(here)
library(ggplot2)
library(gganimate)
library(udpipe)
library(randomForest)
library(tidyverse)
library(lme4)
library(factoextra)
library(moments)
library(forecast)
library(fastDummies)
library(NeuralNetTools)
library(parallel)
library(doMC)
library(caret)

numCores <- detectCores()
registerDoMC(cores = numCores)

#Read all files into this RMD file:
df_tracking_1 <- read_csv(here("tracking2018.csv"))
df_tracking_2 <-read_csv(here("tracking2019.csv"))
df_tracking_3 <-read_csv(here("tracking2020.csv"))
df_plays <- read_csv(here("plays.csv"))
df_PFFScouting <-  read_csv(here("PFFScoutingData.csv"))
df_games <- read.csv(here("games.csv"))

#Combining tracking data sets:-
df_t <- rbind(df_tracking_2,df_tracking_3)

#Standardizing tracking data so its always in direction of kicking team.
df_tracking <- df_t %>%
                mutate(x = ifelse(playDirection == "left", 120-x, x),
                       y = ifelse(playDirection == "left", 160/3 - y, y))
```


```{r}
#Data style 3:

#creating data frame that will only includes Kick Returns that were actually returned. 
df_K <- df_tracking %>%
    #joining the scouting data
    left_join(df_plays, by = c("gameId", "playId")) %>%
    #filtering for kickoff plays only
    filter(specialTeamsPlayType == "Kickoff") %>%
  #filtering for only kicks that were returned
  filter(kickReturnYardage != "NA") %>%
  #Subsetting desireable variables
  select(., time:playDirection, possessionTeam:kickBlockerId,kickReturnYardage) %>% 
  
  #Creating Unique Indefintifer based off nflId, gameId, and playId
  mutate(UKI = unique_identifier(., fields = c("nflId", "gameId","playId"))) %>% 
  
  #Create Unique Identifier for each unique play across all games and seasons
  mutate(UPI = unique_identifier(., fields = c("gameId","playId"))) %>%
  
  #Joining with PFF scouting data table
  left_join(df_PFFScouting) %>%
  #filter(., kickType == "D") %>% 
    #joining data with games data set
  inner_join(df_games)  %>% 

  #Sorting teams by home and away for each game into one column
  mutate(Teams = ifelse(team=="home",homeTeamAbbr,visitorTeamAbbr)) %>% 
  
  #Sorting by which team is the Kicking and Receiving team for each game 
  mutate(RecTeam = if_else(possessionTeam==Teams,"Kick","Rec")) %>% 

  #Creating a new variable where I change a categorical level of the position variable to differentiate the kick returner from the rest (The "A" prefix was added to be able to run code later that matches the positioning of the variable)
  group_by(UPI,frameId) %>%  mutate(a_pos = replace(position,nflId==returnerId,"AKR")) 

head(df_K)


#Arranging the data by the new position variable, so kick returner is at the top 
df_KOP <- df_K %>% arrange(.,a_pos) %>% 
  
  #Subsetting the data to the moment the Kick Returner receives the kick
 filter(., event == "kickoff")   %>% 
  
  #Subset to only include the Kicking Team
  filter(.,RecTeam == "Kick") %>% 
  
  #Creating categorical variable to differentiate between Kicker and non-kicker
  mutate(KickerYN = ifelse(nflId==kickerId,"A","B")) %>% 
  
  #Cleaning up errors in the data to ensure only players in KickerYN level A , is a kicker
  filter(., returnerId != "NA") %>%
  
  #Arrange with the kickers at the top
  arrange(., KickerYN) %>% 
  
  #Reset group and filter at the point of the kickoff and subset by each unique play 
   group_by(UPI) %>% 
  
  #Creating a variable to find the distance from the kicker
  mutate(DistKick = y - first(y)) %>%  
  
  #ungrouping the data and filter to delete the football out of the data 
  ungroup () %>% filter(., displayName != "football") %>%
  
  #delete observations that clearly aren't a part of a normal kickoff
  #filter(DistKick > -30) %>% 
  
  #Arrange by the Distance Kick
  arrange(DistKick) %>% 
  
  #Group by each play each unique play 
  group_by(UPI)  %>%  
  
  #Ranking by each distance for each play to determine the position from the kicker, setting up KOP (KOP = Kickoff position)
  mutate(KOP = rank(DistKick)) %>% 
  
  #Recoding the factors to match the position on the kickoff 
  mutate(KOP = as.factor(KOP), KOP = fct_recode(KOP, "L1" ="1", "L2"="2","L3"="3","L4"="4","L5"="5", "K"="6","R5"="7","R4"="8","R3"="9","R2"="10","R1"="11")) 

#Selecting the unique identifier and the Kickoff Position, and ungrouping the data
df_KOP <- df_KOP %>% select(., UKI, KOP)  %>% ungroup()

#head df_KOP
head(df_KOP)

df_FDS <- df_KOP

#Setting up main kickoff tracking dataset 
# Creating Inital Kickoff Tracking (KOT_I) by joining main tracking and Kickoff Position by unique identifier 
df_KOT_I <- df_K %>% left_join(df_KOP, by = "UKI") %>%
  
  #Filter by the moment the kick was receieved by the kick returner
  filter(., event == "kick_received") 

#Converting kickoff position to character and replacing NAs with 0s
df_KOT_I$KOP <- df_KOT_I$KOP %>% as.character() %>% replace_na(0)

#head df_KOT_I
head(df_KOT_I)

#Creating Main Kickoff tracking data set 
df_KOT<- df_KOT_I %>% 
  
  #Mutating Kickoff Position to add unique level of Kick Returner
  mutate(KOP = replace(KOP,nflId==returnerId,"KR")) %>%
  
  #Filtering out the football from the tracking data and arrange by position 
  filter(., displayName != "football") %>% arrange(.,a_pos) %>% 
  
  #Renaming the key variables that were altered by the table join
  rename(.,UPI = UPI.x ) %>% 
  
  #Then grouping by each unique frame in each unique play
  group_by(UPI) %>%
  
  #Then creating the distance that each player/observation is from the Kick Returner and ungroup
   mutate(Euclidean = as.matrix(dist(cbind(x, y)))[1, ]) %>% ungroup()

#Creating cleaning data set to fill in Missing Kick returner position values by proximity to KR
df_clean <- df_KOT %>%
  
  #Filtering for absent Position values
  filter(., KOP == "0") %>% 
  
  #Selecting only variables needed to fill KOP values 
  select(., x:dir,nflId,frameId:playDirection,kickReturnYardage:a_pos,KOP:Euclidean) %>%
  
  #Arrange by the Euclidean values 
  arrange(Euclidean) %>% 
  
  #Group by each play each unique play 
  group_by(UPI) %>% 
  
  #Ranking by each distance for each play to determine the position from the KR
  mutate(KOP = rank(Euclidean)) %>%
  
  #Filtering out plays where data had a typo and didn't follow previous code
  filter(., KOP < 11) %>% filter(., Euclidean > 0.0) %>%
  
  #Selecting Kick Return Euclidean Position and unique Identifier
  select(., UKI, KOP)

#print df_KOT
head(df_KOT)

#Creating Merge data set to combine all values of Kickoff Position into one column 
df_KRKO <- df_KOT %>% left_join(df_clean, by="UKI")%>% 
  
  #Identifying NAs in original KOP column to show where df_clean$KOP values will go
  mutate(KOP.x = replace(KOP.x, KOP.x==0, NA)) %>% 
  
  #Defining new Total KOP (TKOP), that uses both KOP columns to create the complete column
  transform(., TKOP = ifelse(!is.na(KOP.x), KOP.x, KOP.y)) %>%
  
  #Selecting variables of interest
  select(., x:dir,frameId:playDirection,kickReturnYardage:UPI.x,hangTime:kickoffReturnFormation, Teams:a_pos,Euclidean,TKOP) %>% 
  
  #Filter out any plays where TKOP could not be identified
  filter(., TKOP != "NA") %>% 
  
  #Rename variables that were altered by the table join
  rename(.,UPI = UPI.x )%>%
  
  #Arranging the data set by Euclidean Distances
  arrange(RecTeam,Euclidean) %>%
  
  #Grouping by 
  group_by(UPI) %>% 
  
  #Creating Unique Ident variable for only the Kicking team based on Euclidean Position from the KR 
  mutate(UNI_KICK = row_number()) %>% 
  
  filter(.,UNI_KICK < 23) %>% 
  
 ungroup() %>%
  
  group_by(UPI) %>% filter(n()>20) %>%
  
  
  group_by(UPI) %>%
  
  arrange(UNI_KICK) %>%

  #Creating Total Euclidean for Kick Team
  mutate(KTE = sum(Euclidean[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating Total Euclidean for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(KTC2 = sum(Euclidean[UNI_KICK[c(1:2)]])) %>%
  
   #Creating Total Euclidean for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(KTC3T6 = sum(Euclidean[UNI_KICK[c(3:6)]])) %>% 
  
    #Creating Total Euclidean for Return Team
  mutate(RTE = sum(Euclidean[UNI_KICK[c(12:22)]]))  %>% 
  
  #Creating Total Euclidean for Return Team (First 2 closest players, EXCLUDING KR)
  mutate(RTC2 = sum(Euclidean[UNI_KICK[c(13:14)]])) %>%
  
   #Creating Total Euclidean for Return Team (3-7th closest players, EXCLUDING KR)
  mutate(RTC3T6 = sum(Euclidean[UNI_KICK[c(15:18)]])) %>% 
  
   #Creating Mean Euclidean for Kick Team
  mutate(KME = mean(Euclidean[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating Mean Euclidean for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(KMC2 = mean(Euclidean[UNI_KICK[c(1:2)]])) %>%
  
   #Creating Mean Euclidean for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(KMC3T6 = mean(Euclidean[UNI_KICK[c(3:6)]])) %>% 
  
    #Creating Mean Euclidean for Kick Team
  mutate(RME = mean(Euclidean[UNI_KICK[c(12:22)]]))  %>% 
  
  #Creating Mean Euclidean for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(RMC2 = mean(Euclidean[UNI_KICK[c(13:14)]])) %>%
  
   #Creating Mean Euclidean for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(RMC3T6 = mean(Euclidean[UNI_KICK[c(15:18)]])) %>% 
  
    #Creating sd Euclidean for Kick Team
  mutate(KSDE = sd(Euclidean[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating sd Euclidean for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(KSDC2 = sd(Euclidean[UNI_KICK[c(1:2)]])) %>%
  
   #Creating sd Euclidean for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(KSDC3T6 = sd(Euclidean[UNI_KICK[c(3:6)]])) %>% 
  
    #Creating sd Euclidean for Kick Team
  mutate(RSDE = sd(Euclidean[UNI_KICK[c(12:22)]]))  %>% 
  
  #Creating sd Euclidean for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(RSDC2 = sd(Euclidean[UNI_KICK[c(13:14)]])) %>%
  
   #Creating sd Euclidean for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(RSD3T6 = sd(Euclidean[UNI_KICK[c(15:18)]])) %>% 
  

#Creating Total a for Kick Team
  mutate(AccKTE = sum(a[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating Total a for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(AccKTC2 = sum(a[UNI_KICK[c(1:2)]])) %>%
  
   #Creating Total a for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(AccKTC3T6 = sum(a[UNI_KICK[c(3:6)]])) %>% 
  
#Creating Mean a for Kick Team
  mutate(AccKME = mean(a[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating Mean a for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(AccKMC2 = mean(a[UNI_KICK[c(1:2)]])) %>%
  
   #Creating Mean a for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(AccKMC3T6 = mean(a[UNI_KICK[c(3:6)]])) %>%

  #Creating sd a for Kick Team
  mutate(AccKSDE = sd(a[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating sd a for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(AccKSDC2 = sd(a[UNI_KICK[c(1:2)]])) %>%
  
   #Creating sd a for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(AccKSDC3T6 = sd(a[UNI_KICK[c(3:6)]])) %>% 
  
#Creating Total s for Kick Team
  mutate(SPKTE = sum(s[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating Total s for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(SPKTC2 = sum(s[UNI_KICK[c(1:2)]])) %>%
  
   #Creating Total s for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(SPKTC3T6 = sum(s[UNI_KICK[c(3:6)]])) %>% 
  
#Creating Mean s for Kick Team
  mutate(SPKME = mean(s[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating Mean s for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(SPKMC2 = mean(s[UNI_KICK[c(1:2)]])) %>%
  
   #Creating Mean s for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(SPKMC3T6 = mean(s[UNI_KICK[c(3:6)]])) %>%

  #Creating sd s for Kick Team
  mutate(SPKSDE = sd(s[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating sd s for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(SPKSDC2 = sd(s[UNI_KICK[c(1:2)]])) %>%
  
   #Creating sd s for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(SPKSDC3T6 = sd(s[UNI_KICK[c(3:6)]])) %>% 
    
    #Creating Total dir for Kick Team
  mutate(DirKTE = sum(dir[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating Total dir for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(DirKTC2 = sum(dir[UNI_KICK[c(1:2)]])) %>%
  
   #Creating Total dir for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(DirKTC3T6 = sum(dir[UNI_KICK[c(3:6)]])) %>% 
  
#Creating Mean dir for Kick Team
  mutate(DirKME = mean(dir[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating Mean dir for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(DirKMC2 = mean(dir[UNI_KICK[c(1:2)]])) %>%
  
   #Creating Mean dir for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(DirKMC3T6 = mean(dir[UNI_KICK[c(3:6)]])) %>%

  #Creating sd dir for Kick Team
  mutate(DirKSDE = sd(dir[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating sd dir for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(DirKSDC2 = sd(dir[UNI_KICK[c(1:2)]])) %>%
  
   #Creating sd dir for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(DirKSDC3T6 = sd(dir[UNI_KICK[c(3:6)]])) %>% 
    
    #Creating Total o for Kick Team
  mutate(oKTE = sum(o[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating Total o for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(oKTC2 = sum(o[UNI_KICK[c(1:2)]])) %>%
  
   #Creating Total o for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(oKTC3T6 = sum(o[UNI_KICK[c(3:6)]])) %>% 
  
#Creating Mean o for Kick Team
  mutate(oKME = mean(o[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating Mean o for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(oKMC2 = mean(o[UNI_KICK[c(1:2)]])) %>%
  
   #Creating Mean o for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(oKMC3T6 = mean(o[UNI_KICK[c(3:6)]])) %>%

  #Creating sd o for Kick Team
  mutate(oKSDE = sd(o[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating sd o for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(oKSDC2 = sd(o[UNI_KICK[c(1:2)]])) %>%
  
   #Creating sd o for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(oKSDC3T6 = sd(o[UNI_KICK[c(3:6)]]))  %>%
  
  
  #Getting Rid of non-important variables 
  select(., -(assistTackler:Teams)) %>% 
  
  #Seperating out list of missed tacklers into a separate column for each missed tackle
 separate(missedTackler,into = c("MT1","MT2","MT3","MT4"),sep = ";") %>% 
  
  #Replace missing values in missed tackle columns and Penalty yards column
  replace_na(list(MT1 = 0, MT2 =0, MT3 = 0, MT4 = 0, penaltyYards = 0)) %>%
  
  #Binary Encoding the Missed Tackle Columns to show just the prescence of the ith missed tackle
  mutate(NMT1 = ifelse(MT1 == 0 ,0,1)) %>% mutate(NMT2 = ifelse(MT2 == 0 ,0,1)) %>%
  mutate(NMT3 = ifelse(MT3 == 0 ,0,1)) %>% mutate(NMT4 = ifelse(MT4 == 0 ,0,1)) %>%
  
#Add together the binary values of each missed tackle across the rows to get total # of missed tackles on each play, labeled Total Missed Tackles (TMT)
  mutate(TMT = NMT1+NMT2+NMT3+NMT4) %>%
  
  #Take out columns of non-importance at this point 
  dplyr::select(., - (MT1:MT4),-(NMT1:NMT4)) %>%
  
  na.exclude() %>% 
  
  filter(., a_pos=="AKR") %>% 
  
  select(., -dis,-(frameId:playId), -(UKI:UPI), -(RecTeam:UNI_KICK), -playDirection, -(kickType:returnDirectionIntended))  %>% 
  
  dummy_columns(., select_columns = "returnDirectionActual") %>% 
  
  select(., -returnDirectionActual)

#print df_KRKO
head(df_KRKO)

```


```{r}

EDFD <- df_K %>% left_join(df_FDS, by = "UKI") %>% filter(., event == "kick_received") 

EDFD$KOP <- EDFD$KOP %>% as.character() %>% replace_na(0)

head(EDFD)

AEDFD <- EDFD %>% mutate(KOP = replace(KOP,nflId==returnerId,"KR")) %>%
  filter(., displayName != "football") %>% arrange(.,a_pos) %>% 
   rename(.,UPI = UPI.x ) %>% 
  #Then grouping by each unique frame in each unique play
  group_by(gameId,playId,frameId) %>%
  #Then creating the distance that each player/observation is from the Kick Returner
   mutate(Euclidean = as.matrix(dist(cbind(x, y)))[1, ]) %>% 
  ungroup()

head(AEDFD)

NFD <- AEDFD %>% filter(., KOP == "0") %>% select(., x:dir,nflId,frameId:playDirection,kickReturnYardage:a_pos,KOP:Euclidean) %>%
  arrange(Euclidean) %>% 
  #Group by each play each unique play 
  group_by(gameId,playId,frameId) %>%  
  #Ranking by each distance for each play to determine the position from the kicker
  mutate(KOP = rank(Euclidean)) %>%
  filter(., KOP < 11) %>% 
  filter(., Euclidean > 0.0) %>%
  select(., UKI, KOP) 

head(NFD)

TFG <- AEDFD %>% left_join(NFD, by="UKI") %>%  mutate(KOP.x = replace(KOP.x, KOP.x==0, NA)) %>% 
  transform(., TKOP = ifelse(!is.na(KOP.x), KOP.x, KOP.y)) %>% 
  select(., x:dir,frameId.x:playDirection,kickReturnYardage:a_pos,Euclidean,TKOP) %>% 
  filter(., TKOP != "NA") %>% 
  rename(.,frameId = frameId.x ) %>%  rename(.,gameId = gameId.x ) %>%  rename(.,playId = playId.x ) %>% group_by(UPI) %>% filter(n()==22)

TA <- TFG %>% pivot_wider(.,id_cols = UPI, names_from = TKOP  , names_prefix = "Euc", values_from = Euclidean) %>% na.exclude()


TB <- TFG %>% pivot_wider(.,id_cols = c(UPI), names_from = TKOP  , names_prefix = "Sp", values_from = s) %>% na.exclude()

TC <- TFG %>% pivot_wider(.,id_cols = c(UPI), names_from = TKOP  , names_prefix = "Acc", values_from = a) %>% na.exclude()

TD <- TFG %>% pivot_wider(.,id_cols = c(UPI), names_from = TKOP  , names_prefix = "Ori", values_from = o) %>% na.exclude()


TE <- TFG %>% pivot_wider(.,id_cols = c(UPI), names_from = TKOP  , names_prefix = "x", values_from = x) %>% na.exclude()

TF <- TFG %>% pivot_wider(.,id_cols = c(UPI), names_from = TKOP  , names_prefix = "y", values_from = y) %>% na.exclude()

TG <- TFG %>% pivot_wider(.,id_cols = c(UPI), names_from = TKOP  , names_prefix = "dis", values_from = dis) %>% na.exclude()

TH <- TFG %>% pivot_wider(.,id_cols = c(UPI), names_from = TKOP  , names_prefix = "dir", values_from = dir) %>% na.exclude()


DFT <- TA %>% left_join(TB) %>% left_join(TC) %>% left_join(TD) %>% left_join(TE)  %>% 
  left_join(TF) %>% 
  left_join(TG) %>% left_join(TH)

head(DFT)


df_NT <- df_KRKO %>% left_join(DFT, by="UPI") %>% select(., -UPI, -EucKR)
head(df_NT)
```


```{r}
#Checking models for variable

rf_var_test<- randomForest(kickReturnYardage ~., data = df_NT)

I_SCORE_FUNC <- function(RF_TEST){
i_scores <- varImp(RF_TEST ,conditional=TRUE)
#Gathering rownames in 'var'  and converting it to the factor
#to provide 'fill' parameter for the bar chart. 
i_scores <- i_scores %>% tibble::rownames_to_column("var") 
i_scores$var<- i_scores$var %>% as.factor()
#Plotting the bar and polar charts for comparing variables
i_bar <- ggplot(data = i_scores) + 
  geom_bar(
    stat = "identity",#it leaves the data without count and bin
    mapping = aes(x = var, y=Overall, fill = var), 
    show.legend = FALSE,
    width = 1
  ) + 
  labs(x = NULL, y = NULL)
i_bar + coord_polar() + theme_minimal()
i_bar + coord_flip() + theme_minimal()
}

I_SCORE_FUNC(rf_var_test)

#The results lean towards including orientation instead of direction, and more of an emphasis on speed than acceleration

#Creating data set without direction and without any of the mean variables

df_NT_WO <- df_NT %>% select(.,-dir,-(DirKTE:DirKSDC3T6), -(KME:RMC3T6),-(AccKME:AccKMC3T6), -(SPKME:SPKMC3T6), - (DirKME:DirKMC3T6), -(oKME:oKMC3T6) )

head(df_NT_WO)

rf_var_test_1<- randomForest(kickReturnYardage ~., data = df_NT_WO)

I_SCORE_FUNC(rf_var_test_1)


```


```{r}
#Checking for zero variance variables
ZV <- nearZeroVar(df_NT, saveMetrics= TRUE)
  #Results = No variables with 0 variance 


#Original data 

#Getting linear dependence 
lc <- findLinearCombos(df_NT)
#data from without linear dependence 
df_WC <- df_NT[, -lc$remove] 
  #essentially just removed the variables that represented the mean
# Filtering out correlated variables 
descrCor <-  cor(df_WC)
highCorr <- sum(abs(descrCor[upper.tri(descrCor)]) > .999)
highlyCorDescr <- findCorrelation(descrCor, cutoff = .75)
df_WC <- df_WC[,-highlyCorDescr]
descrCor2 <- cor(df_WC)


#Narrowed down data 

#Getting rid of linear dependence 
lc1 <- findLinearCombos(df_NT_WO)
   # no linear dependence

# Filtering out correlated variables 
descrCor_1 <-  cor(df_NT_WO)
highCorr_1 <- sum(abs(descrCor_1[upper.tri(descrCor_1)]) > .999)
highlyCorDescr_1 <- findCorrelation(descrCor_1, cutoff = .75)
df_NT_WO_1 <- df_NT_WO[,-highlyCorDescr_1]
descrCor2_1 <- cor(df_NT_WO_1)

```

```{r}
#Transforming main data set
preProcValues2 <- preProcess(df_NT, method = c("center","scale","YeoJohnson"))
train_d <- predict(preProcValues2, df_NT)

head(train_d)

#Transforming cleaned data sets
preProcValues3 <- preProcess(df_NT_WO, method = c("center","scale","YeoJohnson"))
train_d_1 <- predict(preProcValues3, df_NT_WO)

head(train_d_1)

preProcValues4 <- preProcess(df_WC, method = c("center","scale","YeoJohnson"))
train_d_2 <- predict(preProcValues4, df_WC)

head(train_d_2)
#Getting rid of linear dependence 
lc2 <- findLinearCombos(train_d)
df_TD <- train_d[, -lc2$remove]

# Filtering out correlated variables 
descrCor_3 <-  cor(df_TD)
highCorr_3 <- sum(abs(descrCor_3[upper.tri(descrCor_3)]) > .999)
highlyCorDescr_3 <- findCorrelation(descrCor_3, cutoff = .75)
df_TD <- df_TD[,-highlyCorDescr_3]
descrCor2_3 <- cor(df_TD)

```

```{r}
#Feature Selection using caret package

#random forest
ctrl <- rfeControl(functions = rfFuncs,
                   method = "cv",
                   verbose = FALSE)

#Checking all datasets created

#df_NT
lmProfile1 <- rfe(x=df_NT[,-7], y=df_NT$kickReturnYardage,
                 rfeControl = ctrl)

#df_NT_WO
#lmProfile2 <- rfe(x=df_NT_WO[,-6], y=df_NT_WO$kickReturnYardage,rfeControl = ctrl)


#df_NT_WO_1
lmProfile3<- rfe(x=df_NT_WO_1[,-1], y=df_NT_WO_1$kickReturnYardage,
                 rfeControl = ctrl)

#df_TD
lmProfile4 <- rfe(x=df_TD[,-4], y=df_TD$kickReturnYardage,
                 rfeControl = ctrl)

#df_WC
lmProfile5 <- rfe(x=df_WC[,-4], y=df_WC$kickReturnYardage,
                 rfeControl = ctrl)

#train_d
lmProfile6 <- rfe(x=train_d[,-7], y=train_d$kickReturnYardage,
                 rfeControl = ctrl)

#train_d1
lmProfile7 <- rfe(x=train_d_1[,-6], y=train_d_1$kickReturnYardage,
                 rfeControl = ctrl)

#train_d2
lmProfile8 <- rfe(x=train_d_2[,-5], y=train_d_2$kickReturnYardage,
                 rfeControl = ctrl)

#conclusion from this step is that the transformed data frequenctly performs better, so thats what will be used from here on out

```


```{r}
#PCA analysis:
#Full transformed data set
preProc_1 <- preProcess(train_d[,-7],method="pca",thresh = 0.85)
trainPC_1 <- predict(preProc_1,train_d[,-7])

#Narrowed down and clean data set
preProc_2 <- preProcess(df_NT_WO_1[,-5],method="pca",thresh = 0.85)
trainPC_2 <- predict(preProc_2,df_NT_WO_1[,-5])


#Full transformed data set
preProc_3 <- preProcess(df_TD[,-6],method="pca",thresh = 0.85)
trainPC_3 <- predict(preProc_3,df_TD[,-6])

```

```{r}
#Setting up parameter tuning 

fitControl <- trainControl(## 10-fold CV
                           method = "repeatedcv",
                           number = 10,
                           repeats = 10)
```

```{r}
#Neural Networks

  #Original Data

#Parameter grid
#NN_Grid <-  expand.grid(decay = c(0, 0.001, 0.0001,0.00001),size  =c(1,2,3,4,5) )


#Train Model
NN_M1 <- train(kickReturnYardage~., data = train_d, 
               method = "nnet", trControl = fitControl,
               linout = TRUE)

#ds 2 
NN_M2 <- train(kickReturnYardage~., data = train_d_1, 
               method = "nnet", trControl = fitControl,
               linout = TRUE)
#ds 3 
NN_M3 <- train(kickReturnYardage~., data = df_TD, 
               method = "nnet", trControl = fitControl,
               linout = TRUE)

#PCA models

#Train Model
NN_PM1 <- train(kickReturnYardage~., data = train_d, 
               method = "nnet", trControl = fitControl,
               linout = TRUE,preProcess = "pca")

#ds 2 
NN_PM2 <- train(kickReturnYardage~., data = train_d_1, 
               method = "nnet", trControl = fitControl,
               linout = TRUE,preProcess = "pca")
#ds 3 
NN_PM3 <- train(kickReturnYardage~., data = df_TD, 
               method = "nnet", trControl = fitControl,
               linout = TRUE,preProcess = "pca")


```

```{r}
#CART
set.seed(123)

fitControl <- trainControl(## 10-fold CV
                           method = "repeatedcv",
                           number = 10,
                           repeats = 10)

Grid <- expand.grid(cp=seq(0, 0.05, 0.005))


fit.rpartCV <- train(kickReturnYardage ~. , data=df_TD, method = 'rpart', trControl=fitControl, metric='RMSE',maximize=FALSE, tuneGrid = Grid)

##model2b: rpart2 with CV
set.seed(123)

Grid_1<-expand.grid(.maxdepth=seq(5,20,5))

fit.rpart2CV <- train(kickReturnYardage ~. , data=df_TD, method = 'rpart2', trControl=fitControl, metric = 'RMSE', maximize=FALSE, tuneGrid=Grid_1)

plot(fit.rpartCV)
plot(fit.rpart2CV)
```

```{r}
#gradient boosting

Grid_2 <- expand.grid( n.trees = seq(50,1000,50), interaction.depth = c(30), shrinkage = c(0.1), n.minobsinnode = 10 )
fit.gbm <- train(kickReturnYardage ~. , data=df_TD, method = 'gbm', trControl=fitControl,tuneGrid=Grid_2,metric='RMSE',maximize=FALSE)
plot(fit.gbm)

```


```{r}
#glmnet
library(glmnet)

#Parameter grid
#GNET_Grid <-  expand.grid(decay = c(0, 0.001, 0.0001,0.00002),size  =c(1,3,5,6,8,10) )


#Train Model
GNET_M1 <- train(kickReturnYardage~., data = train_d, 
               method = "glmnet", trControl = fitControl)

#ds 2 
GNET_M2 <- train(kickReturnYardage~., data = train_d_1, 
               method = "glmnet", trControl = fitControl)
#ds 3 
GNET_M3 <- train(kickReturnYardage~., data = df_TD, 
               method = "glmnet", trControl = fitControl)

#PCA models

#Train Model
GNET_PM1 <- train(kickReturnYardage~., data = train_d, 
               method = "glmnet", trControl = fitControl,
               linout = TRUE,preProcess = "pca")

#ds 2 
GNET_PM2 <- train(kickReturnYardage~., data = train_d_1, 
               method = "glmnet", trControl = fitControl,preProcess = "pca")
#ds 3 
GNET_PM3 <- train(kickReturnYardage~., data = df_TD, 
               method = "glmnet", trControl = fitControl,preProcess = "pca")


```

```{r}
#elastic net
library(elasticnet)

#Parameter grid
#EN_Grid <-  expand.grid(decay = c(0, 0.001, 0.0001,0.00002),size  =c(1,3,5,6,8,10) )


#Train Model
EN_M1 <- train(kickReturnYardage~., data = train_d, 
               method = "enet", trControl = fitControl,
               linout = TRUE)

#ds 2 
EN_M2 <- train(kickReturnYardage~., data = train_d_1, 
               method = "enet", trControl = fitControl,
               linout = TRUE)
#ds 3 
EN_M3 <- train(kickReturnYardage~., data = df_TD, 
               method = "enet", trControl = fitControl,
               linout = TRUE)

#PCA models

#Train Model
EN_PM1 <- train(kickReturnYardage~., data = train_d, 
               method = "enet", trControl = fitControl,preProcess = "pca")

#ds 2 
EN_PM2 <- train(kickReturnYardage~., data = train_d_1, 
               method = "enet", trControl = fitControl,preProcess = "pca")
#ds 3 
EN_PM3 <- train(kickReturnYardage~., data = df_TD, 
               method = "enet", trControl = fitControl,preProcess = "pca")

```


```{r}
#Ridge Regression:
#Parameter grid
#RD_Grid <-  expand.grid(decay = c(0, 0.001, 0.0001,0.00002),size  =c(1,3,5,6,8,10) )


#Train Model
RD_M1 <- train(kickReturnYardage~., data = train_d, 
               method = "ridge", trControl = fitControl)

#ds 2 
RD_M2 <- train(kickReturnYardage~., data = train_d_1, 
               method = "ridge", trControl = fitControl)
#ds 3 
RD_M3 <- train(kickReturnYardage~., data = df_TD, 
               method = "ridge", trControl = fitControl)

#PCA models

#Train Model
RD_PM1 <- train(kickReturnYardage~., data = train_d, 
               method = "ridge", trControl = fitControl,preProcess = "pca")

#ds 2 
RD_PM2 <- train(kickReturnYardage~., data = train_d_1, 
               method = "ridge", trControl = fitControl,preProcess = "pca")
#ds 3 
RD_PM3 <- train(kickReturnYardage~., data = df_TD, 
               method = "ridge", trControl = fitControl,preProcess = "pca")
```

```{r}
#random Forest
#Parameter grid
#RFGrid <-  expand.grid(decay = c(0, 0.001, 0.0001,0.00002), size  =c(1,3,5,6,8,10) )


#Train Model
RFM1 <- train(kickReturnYardage~., data = train_d, 
               method = "rf", trControl = fitControl)

#ds 2 
RFM2 <- train(kickReturnYardage~., data = train_d_1, 
               method = "rf", trControl = fitControl)
#ds 3 
RFM3 <- train(kickReturnYardage~., data = df_TD, 
               method = "rf", trControl = fitControl)

#PCA models

#Train Model
RFPM1 <- train(kickReturnYardage~., data = train_d,method = "rf", trControl = fitControl,preProcess = "pca")

#ds 2 
RFPM2 <- train(kickReturnYardage~., data = train_d_1, 
               method = "rf", trControl = fitControl,preProcess = "pca")
#ds 3 
RFPM3 <- train(kickReturnYardage~., data = df_TD, 
               method = "rf", trControl = fitControl,preProcess = "pca")
```


```{r}
#Linear Models

lm1 <- lm(kickReturnYardage ~. , data = train_d)
lm2 <- lm(kickReturnYardage ~. , data = train_d_1)
lm3 <- lm(kickReturnYardage ~. , data = df_TD)

st1<- step(lm1)
st2<- step(lm2)
st3<- step(lm3)

```


```{r}
#print all obejcts 
lmProfile1
lmProfile3
lmProfile4
lmProfile5
lmProfile6
lmProfile7
lmProfile8



preProc_1
preProc_2
preProc_3


NN_M1
NN_M2
NN_M3

NN_PM1
NN_PM2
NN_PM3


fit.rpartCV
fit.rpart2CV

plot(fit.rpartCV)
plot(fit.rpart2CV)

fit.gbm

plot(fit.gbm)

GNET_M1
GNET_M2
GNET_M3


GNET_PM1
GNET_PM2
GNET_PM3

EN_M1
EN_M2
EN_M3

EN_PM1
EN_PM2
EN_PM3


RD_M1
RD_M2
RD_M3

RD_PM1
RD_PM2
RD_PM3

RFM1
RFM2
RFM3

RFPM1
RFPM2
RFPM3

summary(lm1)
summary(lm2)
summary(lm3)

summary(st1)
summary(st2)
summary(st3)
```

