---
title: "Final KRA"
author: "Eric Rupinski"
date: "1/31/2022"
output: html_document
---

```{r}
#Read in libraries:
library(here)
library(ggplot2)
library(gganimate)
library(udpipe)
library(randomForest)
library(tidyverse)
library(lme4)
library(factoextra)
library(moments)
library(forecast)
library(fastDummies)
library(NeuralNetTools)
library(caret)
library(CAST)
library(parallel)
library(doMC)

#Multicore processing
numCores <- detectCores()
registerDoMC(cores = numCores)


#Read all files into this RMD file:
df_tracking_1 <- read_csv(here("tracking2018.csv"))
df_tracking_2 <-read_csv(here("tracking2019.csv"))
df_tracking_3 <-read_csv(here("tracking2020.csv"))
df_plays <- read_csv(here("plays.csv"))
df_PFFScouting <-  read_csv(here("PFFScoutingData.csv"))
df_games <- read.csv(here("games.csv"))

#Combining tracking data sets:-
df_t <- rbind(df_tracking_2,df_tracking_3)

#Standardizing tracking data so its always in direction of kicking team.
df_tracking <- df_t %>%
                mutate(x = ifelse(playDirection == "left", 120-x, x),
                       y = ifelse(playDirection == "left", 160/3 - y, y))
```

```{r}
#creating data frame that will only includes Kick Returns that were actually returned. 
df_K <- df_tracking %>%
  
    #joining the scouting data
    left_join(df_plays, by = c("gameId", "playId")) %>%
  
    #filtering for kickoff plays only
    filter(specialTeamsPlayType == "Kickoff") %>%
  
  #filtering for only kicks that were returned
  filter(kickReturnYardage != "NA") %>%
  
  #Subsetting desireable variables
  select(., time:playDirection, possessionTeam:kickBlockerId,kickReturnYardage) %>% 
  
  #Creating Unique Indefintifer based off nflId, gameId, and playId
  mutate(UKI = unique_identifier(., fields = c("nflId", "gameId","playId"))) %>% 
  
  #Create Unique Identifier for each unique play across all games and seasons
  mutate(UPI = unique_identifier(., fields = c("gameId","playId"))) %>%
  
  #Joining with PFF scouting data table
  left_join(df_PFFScouting) %>%
  
  #joining data with games data set
  inner_join(df_games)  %>% 

  #Sorting teams by home and away for each game into one column
  mutate(Teams = ifelse(team=="home",homeTeamAbbr,visitorTeamAbbr)) %>% 
  
  #Sorting by which team is the Kicking and Receiving team for each game 
  mutate(RecTeam = if_else(possessionTeam==Teams,"Kick","Rec")) %>% 

  #Creating a new variable where I change a categorical level of the position variable to differentiate the kick returner from the rest (The "A" prefix was added to be able to run code later that matches the positioning of the variable)
  group_by(UPI,frameId) %>%  mutate(a_pos = replace(position,nflId==returnerId,"AKR"))

#New TEst section 
DF_RD <- df_K %>%filter(a_pos == "AKR") %>% filter(., event == "tackle") %>% mutate(KR_X = x) %>% select(.,gameId, playId, frameId, KR_X , UPI) %>% ungroup()

DF_K1 <- df_K %>% left_join(DF_RD, by = c("UPI") ) %>% filter(., event=="kick_received") 

```

```{r}
#Arranging the data by the new position variable, so kick returner is at the top 
df_KOP <- df_K %>% arrange(.,a_pos) %>% 
  
  #Subsetting the data to the moment the Kick Returner receives the kick
 filter(., event == "kickoff")   %>% 
  
  #Subset to only include the Kicking Team
  filter(.,RecTeam == "Kick") %>% 
  
  #Creating categorical variable to differentiate between Kicker and non-kicker
  mutate(KickerYN = ifelse(nflId==kickerId,"A","B")) %>% 
  
  #Cleaning up errors in the data to ensure only players in KickerYN level A , is a kicker
  filter(., returnerId != "NA") %>%
  
  #Arrange with the kickers at the top
  arrange(., KickerYN) %>% 
  
  #Reset group and filter at the point of the kickoff and subset by each unique play 
   group_by(UPI) %>% 
  
  #Creating a variable to find the distance from the kicker
  mutate(DistKick = y - first(y)) %>%  
  
  #ungrouping the data and filter to delete the football out of the data 
  ungroup () %>% filter(., displayName != "football") %>%
  
  #Arrange by the Distance Kick
  arrange(DistKick) %>% 
  
  #Group by each play each unique play 
  group_by(UPI)  %>%  
  
  #Ranking by each distance for each play to determine the position from the kicker, setting up KOP (KOP = Kickoff position)
  mutate(KOP = rank(DistKick)) %>% 
  
  #Recoding the factors to match the position on the kickoff 
  mutate(KOP = as.factor(KOP), KOP = fct_recode(KOP, "L1" ="1", "L2"="2","L3"="3","L4"="4","L5"="5", "K"="6","R5"="7","R4"="8","R3"="9","R2"="10","R1"="11")) 

#Selecting the unique identifier and the Kickoff Position, and ungrouping the data
df_KOP <- df_KOP %>% select(., UKI, KOP)  %>% ungroup()

#Create data set for later use 
df_FDS <- df_KOP


df_KOT_I <- DF_K1 %>% left_join(df_KOP, by = "UKI") %>% 
  
  #Filter by the moment the kick was receieved by the kick returner
  filter(., event == "kick_received") 

#Converting kickoff position to character and replacing NAs with 0s
df_KOT_I$KOP <- df_KOT_I$KOP %>% as.character() %>% replace_na(0)



#Creating Main Kickoff tracking data set 
df_KOT<- df_KOT_I %>% 
  
  #Mutating Kickoff Position to add unique level of Kick Returner
  mutate(KOP = replace(KOP,nflId==returnerId,"KR")) %>%
  
  #Filtering out the football from the tracking data and arrange by position 
  filter(., displayName != "football") %>% arrange(.,a_pos) %>% 
  
  #Renaming the key variables that were altered by the table join
  rename(.,UPI = UPI.x ) %>% 
  
  #Then grouping by each unique frame in each unique play
  group_by(UPI) %>%
  
  #Then creating the distance that each player/observation is from the Kick Returner and ungroup
  mutate(Euclidean = as.matrix(dist(cbind(x, y)))[1, ]) %>% ungroup()



#Creating cleaning data set to fill in Missing Kick returner position values by proximity to KR
df_clean <- df_KOT %>%
  
  #Filtering for absent Position values
  filter(., KOP == "0") %>% 
  
  #Selecting only variables needed to fill KOP values 
  select(., x:dir,nflId,frameId.x:playDirection,kickReturnYardage:a_pos,KOP:Euclidean,KR_X ) %>%
  
  #Arrange by the Euclidean values 
  arrange(Euclidean) %>% 
  
  #Group by each play each unique play 
  group_by(UPI) %>% 
  
  #Ranking by each distance for each play to determine the position from the KR
  mutate(KOP = rank(Euclidean)) %>%
  
  #Filtering out plays where data had a typo and didn't follow previous code
  filter(., KOP < 11) %>% filter(., Euclidean > 0.0) %>%
  
  #Selecting Kick Return Euclidean Position and unique Identifier
  select(., UKI, KOP)



#Creating Merge data set to combine all values of Kickoff Position into one column 
df_KRKO <- df_KOT %>% left_join(df_clean, by="UKI")%>% 
  
  #Identifying NAs in original KOP column to show where df_clean$KOP values will go
  mutate(KOP.x = replace(KOP.x, KOP.x==0, NA)) %>% 
  
  #Defining new Total KOP (TKOP), that uses both KOP columns to create the complete column
  transform(., TKOP = ifelse(!is.na(KOP.x), KOP.x, KOP.y)) %>%
  
  #Selecting variables of interest
  select(., x:dir,frameId.x:playDirection,kickReturnYardage:UPI.x,hangTime:kickoffReturnFormation, Teams:a_pos,Euclidean,TKOP,KR_X) %>% 
  
  #Filter out any plays where TKOP could not be identified
  filter(., TKOP != "NA") %>% 
  
  #Rename variables that were altered by the table join
  rename(.,UPI = UPI.x )%>%
  
  #Arranging the data set by Euclidean Distances
  arrange(RecTeam,Euclidean) %>%
  
  #Grouping by 
  group_by(UPI) %>% 
  
  #Creating Unique Ident variable for only the Kicking team based on Euclidean Position from the KR 
  mutate(UNI_KICK = row_number()) %>% 
  
  #Getting rid of play that didn't sort correctly 
  filter(.,UNI_KICK < 23) %>% ungroup() %>%
  
  #Group by unique play id, and filtering the lower bound to make sure every play has exactly 22 obs.
  group_by(UPI) %>% filter(n()>20) %>%
  
  #arrange by UNI_KICK
  arrange(UNI_KICK) %>%

  #Creating Total Euclidean for Kick Team
  mutate(KTE = sum(Euclidean[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating Total Euclidean for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(KTC2 = sum(Euclidean[UNI_KICK[c(1:2)]])) %>%
  
   #Creating Total Euclidean for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(KTC3T6 = sum(Euclidean[UNI_KICK[c(3:6)]])) %>% 
  
    #Creating Total Euclidean for Return Team
  mutate(RTE = sum(Euclidean[UNI_KICK[c(12:22)]]))  %>% 
  
  #Creating Total Euclidean for Return Team (First 2 closest players, EXCLUDING KR)
  mutate(RTC2 = sum(Euclidean[UNI_KICK[c(13:14)]])) %>%
  
   #Creating Total Euclidean for Return Team (3-7th closest players, EXCLUDING KR)
  mutate(RTC3T6 = sum(Euclidean[UNI_KICK[c(15:18)]])) %>% 
  
   #Creating Mean Euclidean for Kick Team
  mutate(KME = mean(Euclidean[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating Mean Euclidean for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(KMC2 = mean(Euclidean[UNI_KICK[c(1:2)]])) %>%
  
   #Creating Mean Euclidean for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(KMC3T6 = mean(Euclidean[UNI_KICK[c(3:6)]])) %>% 
  
    #Creating Mean Euclidean for Kick Team
  mutate(RME = mean(Euclidean[UNI_KICK[c(12:22)]]))  %>% 
  
  #Creating Mean Euclidean for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(RMC2 = mean(Euclidean[UNI_KICK[c(13:14)]])) %>%
  
   #Creating Mean Euclidean for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(RMC3T6 = mean(Euclidean[UNI_KICK[c(15:18)]])) %>% 
  
    #Creating sd Euclidean for Kick Team
  mutate(KSDE = sd(Euclidean[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating sd Euclidean for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(KSDC2 = sd(Euclidean[UNI_KICK[c(1:2)]])) %>%
  
   #Creating sd Euclidean for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(KSDC3T6 = sd(Euclidean[UNI_KICK[c(3:6)]])) %>% 
  
    #Creating sd Euclidean for Kick Team
  mutate(RSDE = sd(Euclidean[UNI_KICK[c(12:22)]]))  %>% 
  
  #Creating sd Euclidean for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(RSDC2 = sd(Euclidean[UNI_KICK[c(13:14)]])) %>%
  
   #Creating sd Euclidean for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(RSD3T6 = sd(Euclidean[UNI_KICK[c(15:18)]])) %>% 

#Creating Total a for Kick Team
  mutate(AccKTE = sum(a[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating Total a for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(AccKTC2 = sum(a[UNI_KICK[c(1:2)]])) %>%
  
   #Creating Total a for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(AccKTC3T6 = sum(a[UNI_KICK[c(3:6)]])) %>% 
  
#Creating Mean a for Kick Team
  mutate(AccKME = mean(a[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating Mean a for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(AccKMC2 = mean(a[UNI_KICK[c(1:2)]])) %>%
  
   #Creating Mean a for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(AccKMC3T6 = mean(a[UNI_KICK[c(3:6)]])) %>%

  #Creating sd a for Kick Team
  mutate(AccKSDE = sd(a[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating sd a for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(AccKSDC2 = sd(a[UNI_KICK[c(1:2)]])) %>%
  
   #Creating sd a for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(AccKSDC3T6 = sd(a[UNI_KICK[c(3:6)]])) %>% 
  
#Creating Total s for Kick Team
  mutate(SPKTE = sum(s[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating Total s for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(SPKTC2 = sum(s[UNI_KICK[c(1:2)]])) %>%
  
   #Creating Total s for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(SPKTC3T6 = sum(s[UNI_KICK[c(3:6)]])) %>% 
  
#Creating Mean s for Kick Team
  mutate(SPKME = mean(s[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating Mean s for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(SPKMC2 = mean(s[UNI_KICK[c(1:2)]])) %>%
  
   #Creating Mean s for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(SPKMC3T6 = mean(s[UNI_KICK[c(3:6)]])) %>%

  #Creating sd s for Kick Team
  mutate(SPKSDE = sd(s[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating sd s for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(SPKSDC2 = sd(s[UNI_KICK[c(1:2)]])) %>%
  
   #Creating sd s for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(SPKSDC3T6 = sd(s[UNI_KICK[c(3:6)]])) %>% 
    
    #Creating Total dir for Kick Team
  mutate(DirKTE = sum(dir[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating Total dir for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(DirKTC2 = sum(dir[UNI_KICK[c(1:2)]])) %>%
  
   #Creating Total dir for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(DirKTC3T6 = sum(dir[UNI_KICK[c(3:6)]])) %>% 
  
#Creating Mean dir for Kick Team
  mutate(DirKME = mean(dir[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating Mean dir for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(DirKMC2 = mean(dir[UNI_KICK[c(1:2)]])) %>%
  
   #Creating Mean dir for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(DirKMC3T6 = mean(dir[UNI_KICK[c(3:6)]])) %>%

  #Creating sd dir for Kick Team
  mutate(DirKSDE = sd(dir[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating sd dir for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(DirKSDC2 = sd(dir[UNI_KICK[c(1:2)]])) %>%
  
   #Creating sd dir for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(DirKSDC3T6 = sd(dir[UNI_KICK[c(3:6)]])) %>% 
    
    #Creating Total o for Kick Team
  mutate(oKTE = sum(o[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating Total o for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(oKTC2 = sum(o[UNI_KICK[c(1:2)]])) %>%
  
   #Creating Total o for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(oKTC3T6 = sum(o[UNI_KICK[c(3:6)]])) %>% 
  
#Creating Mean o for Kick Team
  mutate(oKME = mean(o[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating Mean o for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(oKMC2 = mean(o[UNI_KICK[c(1:2)]])) %>%
  
   #Creating Mean o for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(oKMC3T6 = mean(o[UNI_KICK[c(3:6)]])) %>%

  #Creating sd o for Kick Team
  mutate(oKSDE = sd(o[UNI_KICK[c(1:11)]]))  %>% 
  
  #Creating sd o for Kick Team (First 2 closest players, EXCLUDING KR)
  mutate(oKSDC2 = sd(o[UNI_KICK[c(1:2)]])) %>%
  
   #Creating sd o for Kick Team (3-7th closest players, EXCLUDING KR)
  mutate(oKSDC3T6 = sd(o[UNI_KICK[c(3:6)]]))  %>%
  
  
  #Getting Rid of non-important variables 
  select(., -(assistTackler:Teams)) %>% 
  
  #Seperating out list of missed tacklers into a separate column for each missed tackle
 separate(missedTackler,into = c("MT1","MT2","MT3","MT4"),sep = ";") %>% 
  
  #Replace missing values in missed tackle columns and Penalty yards column
  replace_na(list(MT1 = 0, MT2 =0, MT3 = 0, MT4 = 0, penaltyYards = 0)) %>%
  
  #Binary Encoding the Missed Tackle Columns to show just the prescence of the ith missed tackle
  mutate(NMT1 = ifelse(MT1 == 0 ,0,1)) %>% mutate(NMT2 = ifelse(MT2 == 0 ,0,1)) %>%
  mutate(NMT3 = ifelse(MT3 == 0 ,0,1)) %>% mutate(NMT4 = ifelse(MT4 == 0 ,0,1)) %>%
  
#Add together the binary values of each missed tackle across the rows to get total # of missed tackles on each play, labeled Total Missed Tackles (TMT)
  mutate(TMT = NMT1+NMT2+NMT3+NMT4) %>%
  
  #Take out columns of non-importance at this point 
  dplyr::select(., - (MT1:MT4),-(NMT1:NMT4)) %>%
  
  #exclude any NA values
 #na.exclude() %>% 
  
  #filter for only the KR
  filter(., a_pos=="AKR") %>% 
  
  #Getting rid of variables not needed 
  select(., -dis,-(frameId.x:playId.x), -(UKI:UPI), -RecTeam,-UNI_KICK, -playDirection, -(kickType:returnDirectionIntended))

```



```{r}
# Creating data set with Kickoff position and Euclidean distances 
KOEUC <- DF_K1 %>% 
  
  #Left join with the point in the data set from before thats ideal to build on
  left_join(df_FDS, by = "UKI") %>% 
  
  #filter at the moment of the KR receiving the ball
  filter(., event == "kick_received") 

#adjust kickoff position as character variable, and replace NAs with 0 
KOEUC$KOP <- KOEUC$KOP %>% as.character() %>% replace_na(0)




#Adjusting KOEUC to prepare for pivot
AKOEUC <- KOEUC %>% 
  
  #Set the KR was a unqiue individual on the return team
  mutate(KOP = replace(KOP,nflId==returnerId,"KR")) %>%
  
  #filter out the football from the data and arrange by the KR first 
  filter(., displayName != "football") %>% arrange(.,a_pos) %>% 
  
  #Rename a variable that was change in the table join 
   rename(.,UPI = UPI.x ) %>% 
  
  #Then grouping by each unique UPI 
  group_by(UPI) %>%
  
  #Then creating the distance that each player/observation is from the Kick Returner
   mutate(Euclidean = as.matrix(dist(cbind(x, y)))[1, ]) %>% ungroup()


#Create another table to merge with AKOEUC called NFD
NFD <- AKOEUC %>% 
  
  #filter for every player on the return team besides the KR
  filter(., KOP == "0") %>% 
  
  #select variables of interest 
  select(., x:dir,nflId,frameId.x:playDirection,kickReturnYardage:a_pos,KOP:Euclidean,KR_X) %>%
  
  #arrange by the Euclidean
  arrange(Euclidean) %>% 
  
  #Group by UPI
  group_by(UPI) %>%  
  
  #Ranking by each distance for each play to determine the position from the KR
  mutate(KOP = rank(Euclidean)) %>%
  
  #filter for any outlier or mistake in the code
  filter(., KOP < 11) %>%  filter(., Euclidean > 0.0) %>%
  
  #select the new filled KOP variable 
  select(., UKI, KOP) 


#Data set to combine both data conditions 
KOPDS <- AKOEUC %>% 
  
  #Merge filled return tea data set with filled kicking team data set 
  left_join(NFD, by="UKI")%>%
  
  #replace 0s with NA in original kickoff position 
  mutate(KOP.x = replace(KOP.x, KOP.x==0, NA)) %>% 
  
   #merge the two columns who have complementary missing values 
  transform(., TKOP = ifelse(!is.na(KOP.x), KOP.x, KOP.y)) %>% 
  
  #select variables of interest 
  select(., x:dir,frameId.x:playDirection,kickReturnYardage:a_pos,Euclidean,TKOP,KR_X) %>% 
  
  #filter out any missing value of Kickoff position
  filter(., TKOP != "NA") %>% 
  
  #Rename variables that were changed when the tables joing 
  rename(.,UPI = UPI.x ) %>%
  
  #filter by unique play and only include plays with correct amount of players 
  group_by(UPI) %>% filter(n()==22)

#pivot wider for specific values based on Kickoff Position 

#Euclidean table
TA <- KOPDS %>% pivot_wider(.,id_cols = UPI, names_from = TKOP  , names_prefix = "Euc", values_from = Euclidean) %>% na.exclude()

#Speed table 
TB <- KOPDS %>% pivot_wider(.,id_cols = c(UPI), names_from = TKOP  , names_prefix = "Sp", values_from = s) %>% na.exclude()

#Acceleration table 
TC <- KOPDS %>% pivot_wider(.,id_cols = c(UPI), names_from = TKOP  , names_prefix = "Acc", values_from = a) %>% na.exclude()

#Orientation table
TD <- KOPDS %>% pivot_wider(.,id_cols = c(UPI), names_from = TKOP  , names_prefix = "Ori", values_from = o) %>% na.exclude()



DFT <- TA %>% left_join(TB) %>% left_join(TC) %>% left_join(TD) 
#head of DFT
head(DFT)

DFR <- df_KRKO %>% select(., UPI, a_pos, KR_X)

#Merge DFT with Euclidean values
df_NT <- DFR %>% left_join(DFT, by="UPI") %>% na.exclude() %>% select(., -EucKR)

```


```{r}
#df_NT work

#Multicore processing
numCores <- detectCores()
registerDoMC(cores = numCores)



set.seed(10)
model_1 <- train(df_NT[,4:90],df_NT$KR_X,
               method="rf",tuneGrid=data.frame("mtry"= 9),
               importance=TRUE,ntree=150, 
               trControl=trainControl(method="cv",number=3))

set.seed(10)
ffsmodel_LLO <- ffs(df_NT[,4:90],df_NT$KR_X,metric="Rsquared",
                    method="rf", tuneGrid=data.frame("mtry"=9),
                    verbose=FALSE,ntree=150,importance = TRUE,
                    trControl=trainControl(method="cv"))


rf1 <- randomForest(KR_X ~ . -UPI - a_pos, data = df_NT, importance=TRUE)


#A function that creates a variable importance score
I_SCORE_FUNC <- function(RF_TEST){
i_scores <- varImp(RF_TEST ,conditional=TRUE)
#Gathering rownames in 'var'  and converting it to the factor
#to provide 'fill' parameter for the bar chart. 
i_scores <- i_scores %>% tibble::rownames_to_column("var") 
i_scores$var<- i_scores$var %>% as.factor()
#Plotting the bar and polar charts for comparing variables
i_bar <- ggplot(data = i_scores) + 
  geom_bar(
    stat = "identity",#it leaves the data without count and bin
    mapping = aes(x = var, y=Overall, fill = var), 
    show.legend = FALSE,
    width = 1
  ) + 
  labs(x = NULL, y = NULL)
i_bar + coord_polar() + theme_minimal()
i_bar + coord_flip() + theme_minimal()
}

as<- rf1$importance

predictors <- c("EucL4",	"Euc7",	"Euc6",	"Euc5",	"EucL5",	"Euc9",	"Euc4"	,"Euc8",	"Euc10",	"OriL1",	"EucL2",	"OriL5",	"Euc3",	"Euc2",	"EucK",	"EucL3",	"EucR3")

set.seed(10)
ffsmodel_LLO <- ffs( df_NT[,predictors],df_NT$KR_X ,metric="Rsquared",
                    method="rf", tuneGrid=data.frame("mtry"=9),
                    verbose=FALSE,ntree=150,importance = TRUE,
                    trControl=trainControl(method="cv"))

plot_ffs(ffsmodel_LLO)
```

```{r}
library(readr)
library(keras)
library(DT)
library(tidyverse)
library(tensorflow)
library(cleandata)
```

